// FIND [!] TO BE CHANGED / UPDATED

#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           A,             tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           B,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           C,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           D,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port5,           E,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           F,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           G,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port8,           H,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

// Globals
int direction;
int speed;
long distance;

// [!] Diameter of the wheel in inches
float DIA = 2.75;
float TICKS_PER_INCH = 360/(DIA*PI)

// Functions

// i = +ve when moving forward, -ve moving backward
// d = distance in inches
// s = speed of motor [-127 to 127] +ve and -ve according to i
void moveStraight(int i, long d, int s);

task autonomous()
{
	//nMotorEncoder(B) = 0;
	//nMotorEncoder(D) = 0;
	//nMotorEncoder(E) = 0;
	//nMotorEncoder(G) = 0;
	//nMotorEncoder(H) = 0;
	motor[B] = 127;
	//motor[A] = 60;
	//motor[B] = 60;
	//motor[C] = 60;
	//motor[D] = 60;

	wait1Msec(5000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}

void moveStraight(int i, long d, int s){
	clearTimer(T1);

	nMotorEncoder(B) = 0;
	nMotorEncoder(D) = 0;

	tickGoal = ceil(TICKS_PER_INCH*d*i);

	setMotorTarget(A,tickGoal,s,false);
	setMotorTarget(B,tickGoal,s,false);
	setMotorTarget(C,tickGoal,s,false);
	setMotorTarget(D,tickGoal,s,false);

	while((!getMotorTargetCompleted(A) || !getMotorTargetCompleted(B) || !getMotorTargetCompleted(C) || !getMotorTargetCompleted(D))&time1[T1]<4000)
	{
		sleep(10);
	}
}
